# **Cricket Case Study**



1.   Find mean, median, IQR for Sachin, Rahul, and India
2.   Find the histogram of Sachin's scores with 10 bins
3.   Find mean of Sachin's scores grouped by 25 matches
4.   Find mean of Sachin's scores where he has scored a century
5.   Find mean of Sachin's scores when Rahul has scored less than 10
6.   Find mean for Sachin's scores based on which quartile India's score falls in
7.   For every match find out who has has scored more - Sachin or Rahul
8.   How many more runs does Sachin score on average after having scored x runs
9.   How many matches did Sachin take to score first 1000 runs, next 1000 runs, ...



In [1]:
!head cric_data.tsv

	Sachin Tendulkar	Rahul Dravid	India
0	100	78	342
1	11	62	191
2	8	85	252
3	71	24	307
4	104	17	229
5	18	104	246
6	8	76	226
7	86	74	288
8	12	60	216


# **Problem 1**

In [2]:
import numpy as np

In [3]:
cric_data = np.loadtxt("cric_data.tsv", skiprows=1)

In [4]:
cric_data.shape

(225, 4)

In [5]:
cric_data = cric_data[:, 1:]

In [6]:
cric_data.shape

(225, 3)

In [ ]:
# np.mean(cric_data, axis=0)

In [ ]:
# np.median(cric_data, axis=0)

In [8]:
sachin = cric_data[:, 0]

In [ ]:
# np.mean(sachin)

In [7]:
dravid = cric_data[:, 1]

In [9]:
india=cric_data[:, 2]

In [ ]:
# sachin

In [ ]:
# sachin.shape

In [ ]:
# sachin = sachin.reshape(225,1) #sachin = cric_data[:, 0].reshape(225,1)

In [ ]:
# dravid = cric_data[:, 1].reshape(225,1)

In [ ]:
# dravid.shape

In [ ]:
# india=cric_data[:, 2].reshape(225,1)

In [ ]:
# sachin_percent = np.percentile(sachin, [25,75])

In [ ]:
# sachin_iqr = sachin_percent[1] - sachin_percent[0]

In [ ]:
# sachin_iqr

In [10]:
def stats(col):
  print('Mean' , np.mean(col))
  print('Median' , np.median(col))
  print('IQR' , np.percentile(col, 75) - np.percentile(col, 25))


In [11]:
stats(sachin)

Mean 39.87555555555556
Median 27.0
IQR 57.0


# **Problem 2**

In [ ]:
np.histogram?

In [12]:
np.histogram(sachin, bins=10)

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1]),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

# **Problem 3**

In [13]:
sachin_25s = sachin.reshape(9, 25)

In [14]:
sachin_25s

array([[100.,  11.,   8.,  71., 104.,  18.,   8.,  86.,  12.,  85.,  18.,
          4.,   7.,  37.,  14.,   0.,   4.,   0.,  21.,   1.,  62.,   0.,
        138.,  38.,   2.],
       [ 46.,  65.,   0.,  39.,  48., 141.,  62.,  12.,   1.,  41.,  11.,
          3., 186.,  11.,  27.,  27.,  51.,  18.,  32., 146.,   5.,  45.,
        141.,  12.,  65.],
       [ 27.,   7.,  16.,   2.,  28.,   6., 123., 120.,   7.,   3.,   0.,
         81.,   2.,  54., 122.,   4.,  14.,   0., 100.,  15.,   0.,  57.,
         99.,  37.,  38.],
       [ 32.,  21.,  32.,  40.,   0.,   5.,   8.,   5.,   0.,  50.,  30.,
         37.,  89.,   4.,  98.,  83.,  93.,   0.,  52., 152.,   1.,   8.,
         93.,  45.,  26.],
       [  0.,   1.,   0.,  16.,  47.,  89.,   3.,   1.,  53.,  16.,   0.,
         81.,  14.,  78.,   6., 105., 122.,   9.,   8.,  28.,  35.,  69.,
         13.,  97.,  93.],
       [  2.,  36.,  39.,   2.,  29.,  12.,  19.,  34.,   2., 100.,  44.,
         82.,   0.,  79.,   6.,   9.,   8.,  23.,  

In [15]:
np.mean(sachin_25s, axis=1)

array([33.96, 49.4 , 38.48, 40.16, 39.36, 38.2 , 44.6 , 39.52, 35.2 ])

# **Problem 4,5**

In [16]:
np.mean(sachin[sachin>=100])

125.0

In [17]:
np.mean(sachin[dravid<10])

40.74285714285714

# **Problem 6**

In [18]:
qrs = np.percentile(india, [25, 50, 75, 100])

In [19]:
india.shape

(225,)

In [20]:
qrs = qrs.reshape(4,1)

In [21]:
indices = india < qrs

In [22]:
indices.shape

(4, 225)

In [23]:
sachin[indices[1, :]].shape

(111,)

In [24]:
for i in range(4):
    print(i, np.mean(sachin[indices[i]]))

0 19.672727272727272
1 28.18018018018018
2 31.688622754491018
3 39.799107142857146


# **Problem 7**

In [25]:
snr = cric_data[:, :2]

In [26]:
snr

array([[100.,  78.],
       [ 11.,  62.],
       [  8.,  85.],
       [ 71.,  24.],
       [104.,  17.],
       [ 18., 104.],
       [  8.,  76.],
       [ 86.,  74.],
       [ 12.,  60.],
       [ 85.,  12.],
       [ 18.,  63.],
       [  4., 107.],
       [  7.,  76.],
       [ 37.,   4.],
       [ 14.,   5.],
       [  0.,  33.],
       [  4.,   7.],
       [  0.,   0.],
       [ 21.,  36.],
       [  1.,  66.],
       [ 62.,   0.],
       [  0., 123.],
       [138.,  39.],
       [ 38.,   9.],
       [  2.,  11.],
       [ 46.,  14.],
       [ 65.,   0.],
       [  0.,   0.],
       [ 39.,  26.],
       [ 48.,   4.],
       [141.,  48.],
       [ 62.,   7.],
       [ 12.,  73.],
       [  1.,  86.],
       [ 41.,  32.],
       [ 11.,  82.],
       [  3.,  25.],
       [186., 153.],
       [ 11.,  26.],
       [ 27.,   1.],
       [ 27.,   6.],
       [ 51.,   3.],
       [ 18.,   1.],
       [ 32.,  39.],
       [146.,  30.],
       [  5.,  32.],
       [ 45.,  84.],
       [141.,

In [27]:
rahul_higher = np.argmax(snr, axis=1)

In [28]:
np.sum(rahul_higher)/225

0.4711111111111111

In [29]:
np.where(rahul_higher == 0, 'Sachin', 'Rahul')

array(['Sachin', 'Rahul', 'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Rahul',
       'Sachin', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Sachin',
       'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Sachin',
       'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Sachin', 'Sachin',
       'Sachin', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Sachin',
       'Rahul', 'Rahul', 'Sachin', 'Rahul', 'Sachin', 'Sachin', 'Sachin',
       'Sachin', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Rahul',
       'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Rahul', 'Rahul',
       'Rahul', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Sachin',
       'Sachin', 'Sachin', 'Sachin', 'Sachin'

# **Problem 8**

In [30]:
x_arr = np.arange(0, 101, 5)

In [ ]:
sachin < x_arr

ValueError: ignored

In [31]:
x_arr = x_arr.reshape(x_arr.shape[0],1)

In [32]:
indices = (sachin >= x_arr)

In [33]:
indices

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ..., False,  True,  True],
       [ True,  True, False, ..., False,  True,  True],
       ...,
       [ True, False, False, ..., False, False, False],
       [ True, False, False, ..., False, False, False],
       [ True, False, False, ..., False, False, False]])

In [34]:
sachin[indices[1, :]]

array([100.,  11.,   8.,  71., 104.,  18.,   8.,  86.,  12.,  85.,  18.,
         7.,  37.,  14.,  21.,  62., 138.,  38.,  46.,  65.,  39.,  48.,
       141.,  62.,  12.,  41.,  11., 186.,  11.,  27.,  27.,  51.,  18.,
        32., 146.,   5.,  45., 141.,  12.,  65.,  27.,   7.,  16.,  28.,
         6., 123., 120.,   7.,  81.,  54., 122.,  14., 100.,  15.,  57.,
        99.,  37.,  38.,  32.,  21.,  32.,  40.,   5.,   8.,   5.,  50.,
        30.,  37.,  89.,  98.,  83.,  93.,  52., 152.,   8.,  93.,  45.,
        26.,  16.,  47.,  89.,  53.,  16.,  81.,  14.,  78.,   6., 105.,
       122.,   9.,   8.,  28.,  35.,  69.,  13.,  97.,  93.,  36.,  39.,
        29.,  12.,  19.,  34., 100.,  44.,  82.,  79.,   6.,   9.,   8.,
        23.,  93.,  35.,  63.,  74.,   8., 117.,  39.,  49.,  64.,  43.,
        72.,   5.,  17.,  65.,  20., 141.,  28.,  44.,  27.,  60.,  68.,
       139.,  31.,  44.,  47.,   6.,  17.,  35.,  88., 114.,   7., 127.,
        45.,  33., 110., 146.,   7.,  25.,   9.,  1

In [35]:
indices.shape

(21, 225)

In [36]:
for i in range(x_arr.shape[0]):
  print(x_arr[i, 0], np.mean(sachin[indices[i, :]]) - x_arr[i, 0])


0 39.87555555555556
5 45.61363636363637
10 47.48026315789474
15 47.45255474452555
20 46.824
25 44.10084033613445
30 45.13461538461539
35 43.24742268041237
40 44.05882352941177
45 43.41558441558442
50 43.98529411764706
55 42.317460317460316
60 38.67213114754098
65 37.654545454545456
70 37.08163265306122
75 34.347826086956516
80 30.75
85 28.650000000000006
90 27.400000000000006
95 26.433333333333337
100 25.0


# **Problem 9**

In [37]:
sachin

array([100.,  11.,   8.,  71., 104.,  18.,   8.,  86.,  12.,  85.,  18.,
         4.,   7.,  37.,  14.,   0.,   4.,   0.,  21.,   1.,  62.,   0.,
       138.,  38.,   2.,  46.,  65.,   0.,  39.,  48., 141.,  62.,  12.,
         1.,  41.,  11.,   3., 186.,  11.,  27.,  27.,  51.,  18.,  32.,
       146.,   5.,  45., 141.,  12.,  65.,  27.,   7.,  16.,   2.,  28.,
         6., 123., 120.,   7.,   3.,   0.,  81.,   2.,  54., 122.,   4.,
        14.,   0., 100.,  15.,   0.,  57.,  99.,  37.,  38.,  32.,  21.,
        32.,  40.,   0.,   5.,   8.,   5.,   0.,  50.,  30.,  37.,  89.,
         4.,  98.,  83.,  93.,   0.,  52., 152.,   1.,   8.,  93.,  45.,
        26.,   0.,   1.,   0.,  16.,  47.,  89.,   3.,   1.,  53.,  16.,
         0.,  81.,  14.,  78.,   6., 105., 122.,   9.,   8.,  28.,  35.,
        69.,  13.,  97.,  93.,   2.,  36.,  39.,   2.,  29.,  12.,  19.,
        34.,   2., 100.,  44.,  82.,   0.,  79.,   6.,   9.,   8.,  23.,
        93.,  35.,  63.,  74.,   8., 117.,  39.,  4

In [38]:
sachin_cumsum = np.cumsum(sachin)

In [39]:
np.histogram(sachin_cumsum, bins = np.arange(0,10000,1000))

(array([29, 18, 26, 25, 26, 26, 23, 22, 30]),
 array([   0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000]))